version: '3'
services:
    openwrt:
        build: . 
        restart: unless-stopped
        devices: 
            - /dev/ppp
            - /dev/kmsg
        cap_add: 
            - ALL
            - NET_ADMIN
            - NET_RAW
            - CAP_SYSLOG
            - CAP_NET_BIND_SERVICE
            - CAP_SYS_TTY_CONFIG
        networks:
            - v1f0
            - v1f1
            - v1f2
            - v1f3 
            - v5f0
        entrypoint: 
            - /init

networks:
    v1f0:
        driver: macvlan
        driver_opts:
            parent: enp1s0f0
            macvlan_mode: bridge 
    v1f1:
        driver: macvlan
        driver_opts:
            parent: enp1s0f1
            macvlan_mode: bridge 
    v1f2:
        driver: macvlan
        driver_opts:
            parent: enp1s0f2
            macvlan_mode: bridge
    v1f3:
        driver: macvlan
        driver_opts:
            parent: enp1s0f3
            macvlan_mode: bridge
    v5f0:
        driver: macvlan
        driver_opts:
            parent: enp5s0
            macvlan_mode: bridge
