version: '3'
services:
    openwrt:
        build: . 
        restart: always
        volumes:
            - ./data/openclash:/etc/openclash
        ports:
            - 80:80
            - 9090:9090
        network_mode: bridge
        devices: 
            - /dev/ppp
            - /dev/kmsg
            - /dev/net/tun
        cap_add: 
            - ALL
            - NET_ADMIN
            - NET_RAW
            - CAP_SYSLOG
            - CAP_NET_BIND_SERVICE
            - CAP_SYS_TTY_CONFIG
        entrypoint: 
            - /init
